export const DATA = [
    { id: '1', firstName: 'John', lastName: 'Doe' },
    { id: '2', firstName: 'Jane', lastName: 'Smith' },
    { id: '3', firstName: 'Bob', lastName: 'Johnson' },
    { id: '4', firstName: 'Mike', lastName: 'Jones' },
    { id: '5', firstName: 'Tom', lastName: 'Brown' },
    { id: '6', firstName: 'Tim', lastName: 'Miller' },
    { id: '7', firstName: 'Jim', lastName: 'Davis' },
    { id: '8', firstName: 'Sam', lastName: 'Garcia' },
    { id: '9', firstName: 'Joe', lastName: 'Martinez' },
    { id: '10', firstName: 'Bill', lastName: 'Anderson' },
    { id: '11', firstName: 'Jack', lastName: 'Taylor' },
    { id: '12', firstName: 'Fred', lastName: 'Thomas' },
    { id: '13', firstName: 'Harry', lastName: 'Hernandez' },
    { id: '14', firstName: 'Steve', lastName: 'Moore' },
    { id: '15', firstName: 'Alex', lastName: 'Martin' },
  ];